/* SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026 Oppeko
 */

#ifndef SYSCALL_H
#define SYSCALL_H

#include <stdint.h>

struct syscall_regs {
    uint64_t rax;
    uint64_t rdx;
    uint64_t rsi;
    uint64_t rdi;
    uint64_t r10;
    uint64_t r8;
    uint64_t r9;
    uint64_t r15;
    uint64_t r14;
    uint64_t r13;
    uint64_t r12;
    uint64_t rbx;
    uint64_t rbp;
    uint64_t rcx;
    uint64_t r11;
    uint64_t rsp;
};

enum linux_syscall_nr {
    LINUX_SYS_READ = 0,
    LINUX_SYS_WRITE = 1,
    LINUX_SYS_OPEN = 2,
    LINUX_SYS_CLOSE = 3,
    LINUX_SYS_STAT = 4,
    LINUX_SYS_FSTAT = 5,
    LINUX_SYS_POLL = 7,
    LINUX_SYS_MMAP = 9,
    LINUX_SYS_MPROTECT = 10,
    LINUX_SYS_MUNMAP = 11,
    LINUX_SYS_BRK = 12,
    LINUX_SYS_RT_SIGACTION = 13,
    LINUX_SYS_RT_SIGPROCMASK = 14,
    LINUX_SYS_IOCTL = 16,
    LINUX_SYS_READV = 19,
    LINUX_SYS_WRITEV = 20,
    LINUX_SYS_LSEEK = 8,
    LINUX_SYS_ACCESS = 21,
    LINUX_SYS_PIPE = 22,
    LINUX_SYS_DUP = 32,
    LINUX_SYS_DUP2 = 33,
    LINUX_SYS_SOCKET = 41,
    LINUX_SYS_CONNECT = 42,
    LINUX_SYS_SENDTO = 44,
    LINUX_SYS_RECVFROM = 45,
    LINUX_SYS_CLONE = 56,
    LINUX_SYS_FORK = 57,
    LINUX_SYS_GETPID = 39,
    LINUX_SYS_GETUID = 102,
    LINUX_SYS_GETGID = 104,
    LINUX_SYS_SETUID = 105,
    LINUX_SYS_SETGID = 106,
    LINUX_SYS_GETEUID = 107,
    LINUX_SYS_GETEGID = 108,
    LINUX_SYS_GETPPID = 110,
    LINUX_SYS_PRCTL = 157,
    LINUX_SYS_EXECVE = 59,
    LINUX_SYS_WAIT4 = 61,
    LINUX_SYS_UNAME = 63,
    LINUX_SYS_FCNTL = 72,
    LINUX_SYS_GETCWD = 79,
    LINUX_SYS_CHDIR = 80,
    LINUX_SYS_MKDIR = 83,
    LINUX_SYS_ARCH_PRCTL = 158,
    LINUX_SYS_CLOCK_GETTIME = 228,
    LINUX_SYS_EXIT = 60,
    LINUX_SYS_EXIT_GROUP = 231,
    LINUX_SYS_READLINKAT = 267,
    LINUX_SYS_SET_ROBUST_LIST = 273,
    LINUX_SYS_PRLIMIT64 = 302,
    LINUX_SYS_GETRANDOM = 318,
    LINUX_SYS_STATX = 332,
    LINUX_SYS_RSEQ = 334,
    AOS_SYS_PARTITION_INFO = 500,
    AOS_SYS_PARTITION_CREATE = 501,
    AOS_SYS_PARTITION_DELETE = 502,
    AOS_SYS_PARTITION_TYPE = 503,
    AOS_SYS_BLKDEV_INFO = 504,
    AOS_SYS_PARTITION_WRITE = 505,
    AOS_SYS_MOUNT_INFO = 506,
    AOS_SYS_PARTITION_ROLE = 507,
    AOS_SYS_PARTITION_LAYOUT = 508,
    AOS_SYS_MEM_INFO = 509,
    AOS_SYS_UPTIME_INFO = 510,
    AOS_SYS_DISPLAY_INFO = 511,
    AOS_SYS_DISPLAY_SET = 512,
    AOS_SYS_SHUTDOWN = 513,
    AOS_SYS_RESTART = 514,
    AOS_SYS_TIME_INFO = 515,
    AOS_SYS_USER_INFO = 516,
    AOS_SYS_SUDO_AUTH = 517,
    AOS_SYS_PCI_INFO = 518,
    AOS_SYS_DRIVER_INFO = 519,
    AOS_SYS_GFX_INFO = 520,
    AOS_SYS_GFX_CLEAR = 521,
    AOS_SYS_GFX_PIXEL = 522,
    AOS_SYS_GFX_RECT = 523,
    AOS_SYS_GFX_PRESENT = 524,
    AOS_SYS_INPUT_POLL = 525,
    AOS_SYS_NETDEV_INFO = 526,
    AOS_SYS_NETDEV_SEND = 527,
    AOS_SYS_NETDEV_RECV = 528,
    AOS_SYS_FIRMWARE_INFO = 529,
    AOS_SYS_WIFI_SCAN_INFO = 530,
    AOS_SYS_NETDEV_IPV6_CONFIG = 531,
    AOS_SYS_NETDEV_IPV4_CONFIG = 532,
    AOS_SYS_SOCKET_INFO = 533,
    AOS_SYS_DNS_LOOKUP = 534,
    AOS_SYS_NETDEV_STATS = 535,
    AOS_SYS_WIFI_STATE_INFO = 536,
    AOS_SYS_WIFI_CONTROL = 537,
    AOS_SYS_SOCKET_BIND_NETDEV = 538,
    LINUX_SYS_GETDENTS64 = 217,
    LINUX_SYS_SET_TID_ADDRESS = 218,
    LINUX_SYS_FADVISE64 = 221,
    LINUX_SYS_OPENAT = 257,
    LINUX_SYS_MKDIRAT = 258,
    LINUX_SYS_UNLINKAT = 263,
    LINUX_SYS_NEWFSTATAT = 262,
    LINUX_SYS_FACCESSAT = 269,
};

enum linux_errno {
    LINUX_EPERM = 1,
    LINUX_EACCES = 13,
    LINUX_ENOENT = 2,
    LINUX_E2BIG = 7,
    LINUX_EINTR = 4,
    LINUX_EIO = 5,
    LINUX_EBADF = 9,
    LINUX_ECHILD = 10,
    LINUX_EFAULT = 14,
    LINUX_EEXIST = 17,
    LINUX_ENOTDIR = 20,
    LINUX_EISDIR = 21,
    LINUX_EINVAL = 22,
    LINUX_ENOTTY = 25,
    LINUX_ENODEV = 19,
    LINUX_EMFILE = 24,
    LINUX_ERANGE = 34,
    LINUX_ENOSYS = 38,
};

#endif
